config/routes.rb
RubyWarboats::Application.routes.draw do 

  resources :games do
    resources :ships
    resources :shots
  end

  devise_for :users

  root :to => 'welcome#index'

end

app/models/shot.rb
class Shot < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  
  validates :x, :numericality => {:greater_than_or_equal_to => 1}
  validates :x, :numericality => {:less_than => 11}
  validates :y, :numericality => {:greater_than_or_equal_to => 1}
  validates :y, :numericality => {:less_than => 11}
  
  validate :previous_shot, :on => :create
  
  def previous_shot
    player = Player.find(self.player_id)
    list_of_shots = player.shots
    list_of_shots.each do |current_shot|
      if (self.x == current_shot.x) and (self.y == current_shot.y)
        errors.add(:x, " already has been shot at")
      end
    end
  end
   
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  
  before_filter :authenticate_user!, :get_game
  
  def get_game
    @game = Game.find(params[:game_id])
    #need to call .first because it returns an array otherwise
    @player = current_user.players.where(game_id: @game.id).first
    if @player.nil?
      redirect_to root_url, :notice => "You cannot look at another player's game!"
    end
  end
  
  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shots }
    end
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
    @shot = Shot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shot }
    end
  end

  # GET /shots/new
  # GET /shots/new.json
  def new
    @shot = Shot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shot }
    end
  end

  # GET /shots/1/edit
  def edit
    @shot = Shot.find(params[:id])
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = Shot.new(params[:shot])
    @shot.game_id = @game.id
    @shot.player_id = @player.id

    respond_to do |format|
      if @shot.save
        format.html { redirect_to [@game, @shot], notice: 'Shot was successfully created.' }
        format.json { render json: @shot, status: :created, location: @shot }
      else
        format.html { render action: "new" }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shots/1
  # PUT /shots/1.json
  def update
    @shot = Shot.find(params[:id])

    respond_to do |format|
      if @shot.update_attributes(params[:shot])
        format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot = Shot.find(params[:id])
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to shots_url }
      format.json { head :ok }
    end
  end
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/shots/_form.html.erb
<%= form_for(@shot) do |f| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
      <% @shot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render 'form' %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<h1>Listing shots</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shots.each do |shot| %>
  <tr>
    <td><%= link_to 'Show', [@game, shot] %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shot', new_game_shot_path(@game) %>

app/views/shots/new.html.erb
<h1>Where would you like to attack?</h1>

<%= form_for([@game, @shot]) do |f| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
      <% @shot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= label_tag 'x', 'X coordinate'%>
  <%= f.text_field :x %>
  <br />
  <%= label_tag 'y', 'Y coordinate'%>
  <%= f.text_field :y %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', game_shots_path %>

app/views/shots/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_game_shot_path(@game, @shot) %> |
<%= link_to 'Back', game_shots_path %>