config/routes.rb
RubyWarboats::Application.routes.draw do 

  resources :games do
    resources :ships
    resources :shots
  end

  devise_for :users

  root :to => 'welcome#index'

end

app/models/ship.rb
class Ship < ActiveRecord::Base
  belongs_to :ship_type
  belongs_to :player
  belongs_to :game
  
  validates :x, :numericality => {:greater_than_or_equal_to => 1}
  validates :x, :numericality => {:less_than => 11}
  validates :y, :numericality => {:greater_than_or_equal_to => 1}
  validates :y, :numericality => {:less_than => 11}  
  validate :single_ship_use, :on => :create
  validate :ship_intersection, :on => :create
  validate :valid_ship_location, :on => :create
  
  def ship_intersection
    #make sure where the ships are not intersecting when being placed on the board
    ship_owner = Player.find(self.player_id)
    created_ships = ship_owner.ships
    ranges = ship_range(self)
    created_ships.each do |current_ship|
      other_ranges = ship_range(current_ship)
      if intersect?(ranges, other_ranges)
        errors.add(:ship_type_id, " cannot be created here")
      end
    end
  end
  
  def ship_range(ship)
    if ship.vertical?
      ranges = {xr: ship.x..ship.x, yr: ship.y...(ship.y + ship.ship_type.length)}
    else
      ranges = {xr: ship.x...(ship.x + ship.ship_type.length), yr: ship.y..ship.y}
    end
  end
  
  def intersect?(ranges, other_ranges)
    return ((ranges[:xr].max < other_ranges[:xr].begin or other_ranges[:xr].max < ranges[:xr].begin) and
            (ranges[:yr].max < other_ranges[:yr].begin or other_ranges[:yr].max < ranges[:yr].begin))
  end
  
  def single_ship_use
    #check to see if ship being created already exists for this player in this game
    ship_owner = Player.find(self.player_id)
    created_ships = ship_owner.ships
    created_ships.each do |current_ship|
      if self.ship_type.name == current_ship.ship_type.name
        errors.add(:ship_type_id, " already exists for this game")
      end 
    end
    
  end
  
  def valid_ship_location
    if self.vertical?
      if (self.y + self.health) > 10
        errors.add(:y, " coordinate to high with this ship\'s length")
      end
    else
      if (self.x + self.health) > 10
        errors.add(:x, "x coordinate to high with this ship\'s length")
      end
    end
  end
  
end

app/models/ship_type.rb
class ShipType < ActiveRecord::Base
  has_many :ships
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  # GET /ships
  # GET /ships.json
  
  before_filter :authenticate_user!, :get_game
  
  def get_game
    #find all the ship types for the drop down menu in view
    @shiptypes = ShipType.all
    
    @game = Game.find(params[:game_id])
    @player = current_user.players.where(game_id: @game.id).first
    if @player.nil?
      redirect_to root_url, :notice => "You cannot look at another player's game!"
    end
  end
  
  def index
    @ships = @player.ships

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ships }
    end
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
    @ship = Ship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ship }
    end
  end

  # GET /ships/new
  # GET /ships/new.json
  def new
    
    @ship = Ship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ship }
    end
  end

  # GET /ships/1/edit
  def edit
    @ship = Ship.find(params[:id])
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(params[:ship])
    @ship.game_id = @game.id
    @ship.health = @ship.ship_type.length
    @ship.vertical = true
    @ship.player_id = @player.id

    respond_to do |format|
      if @ship.save
        format.html { redirect_to [@game, @ship], notice: 'Ship was successfully created.' }
        format.json { render json: @ship, status: :created, location: @ship }
      else
        format.html { render action: "new" }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ships/1
  # PUT /ships/1.json
  def update
    @ship = Ship.find(params[:id])

    respond_to do |format|
      if @ship.update_attributes(params[:ship])
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship = Ship.find(params[:id])
    @ship.destroy

    respond_to do |format|
      format.html { redirect_to ships_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.erb
<%= form_for([@game, @ship]) do |f| %>
  <% if @ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
      <% @ship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing ship</h1>

<%= render 'form' %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<h1>Listing ships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ships.each do |ship| %>
  <tr>
  	<td><%= ship.ship_type.name %></td>
    <td><%= link_to 'Show', [@game, ship] %></td>
    <td><%= link_to 'Edit', edit_game_ship_path(@game, ship) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ship', new_game_ship_path(@game) %>

app/views/ships/new.html.erb
<h1>New Ship</h1>
<h4>add the ship to the game board</h4>
<%= form_for([@game, @ship]) do |f| %>
  <% if @ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
      <% @ship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- drop down menu to select ship you want to add to game -->
  <%= f.select :ship_type_id, options_from_collection_for_select(@shiptypes, "id", "name"), :prompt => "Select a ship for the board" %>
  <br />
  <%= label_tag 'x', 'X coordinate'%>
  <%= f.text_field :x %>
  <br />
  <%= label_tag 'y', 'Y coordinate'%>
  <%= f.text_field :y %>
  <br />
  <%= label_tag 'vertical' '?'%>
  <%= f.check_box :vertical %>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_game_ship_path(@game, @ship) %> |
<%= link_to 'Back', game_ships_path %>